# Generated by Django 2.2.3 on 2019-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='status',
            field=models.BooleanField(choices=[(200, 'OK_200'), (404, 'NOT_FOUND_404')]),
        ),
    ]
