# Generated by Django 2.2.3 on 2019-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtcheck', '0002_auto_20190727_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='status',
            field=models.IntegerField(choices=[(200, 'OK'), (404, 'NOT FOUND')]),
        ),
    ]
