# Generated by Django 2.2.3 on 2019-07-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healtcheck', '0003_auto_20190727_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='verificacao',
            options={'verbose_name': 'Verificação', 'verbose_name_plural': 'Verificações'},
        ),
    ]
